"""Add suscripciones y chatbot

Revision ID: ad7a92fa242e
Revises: 
Create Date: 2025-10-02 09:41:31.572367

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ad7a92fa242e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Tabla mensajes del chatbot (coincide con modelo ChatbotMensaje)
    op.create_table(
        'chatbot_mensajes',
        sa.Column('id_mensaje', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('id_usuario', sa.Integer(), nullable=False),
        sa.Column('mensaje_usuario', sa.Text(), nullable=False),
        sa.Column('respuesta_bot', sa.Text(), nullable=False),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('es_premium', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'])
    )
    # Índices
    op.create_index('idx_chatbot_usuario_fecha', 'chatbot_mensajes', ['id_usuario', 'fecha'])

    # Tabla suscripciones (coincide con modelo Suscripcion)
    op.create_table(
        'suscripciones',
        sa.Column('id_suscripcion', sa.Integer(), primary_key=True, nullable=False),
        sa.Column('id_usuario', sa.Integer(), nullable=False),
        sa.Column('tipo_plan', sa.String(length=20), nullable=True),
        sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
        sa.Column('fecha_fin', sa.DateTime(), nullable=True),
        sa.Column('activa', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'])
    )
    op.create_index('idx_suscripcion_usuario_activa', 'suscripciones', ['id_usuario', 'activa'])


def downgrade():
    op.drop_index('idx_suscripcion_usuario_activa', table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index('idx_chatbot_usuario_fecha', table_name='chatbot_mensajes')
    op.drop_table('chatbot_mensajes')
"""Add suscripciones y chatbot

Revision ID: ad7a92fa242e
Revises: 
Create Date: 2025-10-02 09:41:31.572367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7a92fa242e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_conversaciones',
    sa.Column('id_conversacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('mensaje_usuario', sa.Text(), nullable=False),
    sa.Column('respuesta_bot', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('es_premium', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conversacion')
    )
    with op.batch_alter_table('chatbot_conversaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chatbot_conversaciones_es_premium'), ['es_premium'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversaciones_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_chatbot_conversaciones_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('suscripciones',
    sa.Column('id_suscripcion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_plan', sa.String(length=20), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_suscripcion'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suscripciones_activa'), ['activa'], unique=False)
        batch_op.create_index(batch_op.f('ix_suscripciones_id_usuario'), ['id_usuario'], unique=False)

    op.create_table('uso_chatbot',
    sa.Column('id_uso', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('mensajes_usados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_uso'),
    sa.UniqueConstraint('id_usuario', 'fecha', name='uq_usuario_fecha_uso_chatbot')
    )
    with op.batch_alter_table('uso_chatbot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uso_chatbot_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_uso_chatbot_id_usuario'), ['id_usuario'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uso_chatbot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uso_chatbot_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_uso_chatbot_fecha'))

    op.drop_table('uso_chatbot')
    with op.batch_alter_table('suscripciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suscripciones_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_suscripciones_activa'))

    op.drop_table('suscripciones')
    with op.batch_alter_table('chatbot_conversaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chatbot_conversaciones_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversaciones_fecha'))
        batch_op.drop_index(batch_op.f('ix_chatbot_conversaciones_es_premium'))

    op.drop_table('chatbot_conversaciones')
    # ### end Alembic commands ###
